# Safe releases for poppler.
# These releases are chosen from https://packages.ubuntu.com and https://packages.debian.org,
# picking versions from the last 3 releases.


kind = "release"
category = "safe-releases"
target = "poppler"
prefix = "poppler__safe-release"

[[commit-sequences]]
distro = "Ubuntu"
releases = "jammy (22.04LTS), noble (24.04LTS)"
[[commit-sequences.commits]]
ref = "poppler-22.02.0"
harness-patch = "harness.patch"
[[commit-sequences.commits]]
ref = "poppler-24.02.0"
harness-patch = "harness.patch"

[[commit-sequences]]
distro = "Ubuntu"
releases = "noble (24.04LTS), plucky (25.04)"
[[commit-sequences.commits]]
ref = "poppler-24.02.0"
harness-patch = "harness.patch"
[[commit-sequences.commits]]
ref = "poppler-25.03.0"
name = "poppler-25.03.0-ubuntu"
harness-patch = "harness.patch"

[[commit-sequences]]
distro = "Debian"
releases = "bullseye (11), bookworm (12)"
[[commit-sequences.commits]]
ref = "poppler-20.09.0"
harness-patch = "harness-poppler-20.09.0.patch"
[[commit-sequences.commits]]
ref = "poppler-22.12.0"
harness-patch = "harness.patch"

[[commit-sequences]]
distro = "Debian"
releases = "bookworm (12), trixie (13)"
[[commit-sequences.commits]]
ref = "poppler-22.12.0"
harness-patch = "harness.patch"
[[commit-sequences.commits]]
ref = "poppler-25.03.0"
name = "poppler-25.03.0-debian"
harness-patch = "harness.patch"
