# Safe releases for openssl.
# These releases are chosen from https://packages.ubuntu.com and https://packages.debian.org,
# picking versions from the last 3 releases.


kind = "release"
category = "safe-releases"
target = "openssl"
prefix = "openssl__safe-release"

[[commit-sequences]]
distro = "Ubuntu"
releases = "jammy (22.04LTS), noble (24.04LTS)"
[[commit-sequences.commits]]
ref = "openssl-3.0.2"
harness-patch = "harness.patch"
[[commit-sequences.commits]]
ref = "openssl-3.0.13"
harness-patch = "harness.patch"

[[commit-sequences]]
distro = "Ubuntu"
releases = "noble (24.04LTS), plucky (25.04)"
[[commit-sequences.commits]]
ref = "openssl-3.0.13"
harness-patch = "harness.patch"
[[commit-sequences.commits]]
ref = "openssl-3.4.1"
harness-patch = "harness.patch"

[[commit-sequences]]
distro = "Debian"
releases = "bullseye (11), bookworm (12)"
[[commit-sequences.commits]]
ref = "OpenSSL_1_1_1w"
harness-patch = "harness.patch"
[[commit-sequences.commits]]
ref = "openssl-3.0.17"
harness-patch = "harness.patch"

[[commit-sequences]]
distro = "Debian"
releases = "bookworm (12), trixie (13)"
[[commit-sequences.commits]]
ref = "openssl-3.0.17"
harness-patch = "harness.patch"
[[commit-sequences.commits]]
ref = "openssl-3.5.4"
harness-patch = "harness.patch"
